/*****************************************************************************
 * FreeNono - A free implementation of the nonogram game
 * Copyright (c) 2012 Christian Wichmann
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>. 
 *****************************************************************************/
package org.freenono.provider;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.freenono.interfaces.CourseProvider;
import org.freenono.interfaces.NonogramProvider;
import org.freenono.model.Course;

/**
 * Default course for nonogram by seed. This Course provides only one random
 * nonogram generated by the given seed.
 * 
 */
// TODO: save persistent all seed entered ever/in the last year/month/...
public class CourseFromSeed implements CourseProvider {

	private List<String> nonogramList = null;
	private List<NonogramProvider> nonogramProviderList = null;

	public CourseFromSeed() {
		nonogramProviderList = new ArrayList<NonogramProvider>();
		nonogramProviderList.add(new NonogramFromSeed());
		nonogramList = new ArrayList<String>();
		nonogramList.add(nonogramProviderList.get(0).getName()); 
	}
	
	@Override
	public List<String> getNonogramList() {
		return nonogramList;
	}

	@Override
	public Collection<NonogramProvider> getNonogramProvider() {
		return nonogramProviderList;
	}

	@Override
	public Course fetchCourse() {
		// TODO generate default course class with embedded nonograms.
		return null;
	}

	@Override
	public String getCourseName() {
		return nonogramProviderList.get(0).getName();
	}
	
	public String toString() {
		return nonogramProviderList.get(0).getName();
	}

}
